// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function positionsToJs(param) {
  return {
          x: param[/* x */0],
          y: param[/* y */1]
        };
}

function positionsFromJs(param) {
  return /* record */[
          /* x */param.x,
          /* y */param.y
        ];
}

function calculate(t, centerPosition, trayBounds) {
  return positionsFromJs(t.calculate((function () {
                      switch (centerPosition) {
                        case 371331211 : 
                            return "trayCenter";
                        case -272647875 : 
                            return "trayLeft";
                        case -427234744 : 
                            return "trayBottomLeft";
                        case -821073434 : 
                            return "trayRight";
                        case -934206853 : 
                            return "trayBottomRight";
                        case 371331211 : 
                            return "trayCenter";
                        case 912382550 : 
                            return "trayBottomCenter";
                        case 907161884 : 
                            return "topLeft";
                        case 283497767 : 
                            return "topRight";
                        case 591950002 : 
                            return "bottomLeft";
                        case 858208465 : 
                            return "bottomRight";
                        case -269910486 : 
                            return "topCenter";
                        case -958443712 : 
                            return "bottomCenter";
                        case 731702620 : 
                            return "leftCenter";
                        case -745370959 : 
                            return "rightCenter";
                        case 980392437 : 
                            return "center";
                        
                      }
                    })(), trayBounds));
}

exports.positionsToJs = positionsToJs;
exports.positionsFromJs = positionsFromJs;
exports.calculate = calculate;
/* No side effect */
